### ISSUE TITLE
Support self hosted open photo instance.

### ISSUE THREAD

**Issue by alcoralcor** [photo/mobile-android#306]
Trovebox android app offer no possibility to login to self hosted open photo. This should be possible according to Trovebox plans.

**Comment by Notmarrco** [comment]
at last I made it work on my phone ! :+1: 
So the issue was that the certificate was self-signed as we figured some time ago. I asked to add certificate storage to trovebox app to allow use of these certs, but it was a bad idea.

In fact you just have to import your CA cert to your android to make all work. It took me more than one year to figure it out, you can say that I'm quite slow .. :smile: 
To help you out of importing your CA, just use CADroid, an android app that works very well, and I can confirm that now all is working like a charm !
If anyone still bothers I think we can close this issue :smile:  

bye

**Comment by jmathai** [comment]
Thanks for the update @Notmarrco. Better late than never.
